# Generated by Django 5.2 on 2025-04-11 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('La', 'Laptops'), ('De', 'Desktops'), ('Ca', 'Cameras'), ('Vi', 'Vitualdjs'), ('Ph', 'phones')], max_length=200)),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('country', models.CharField(default='Tanzania', max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(choices=[('dodoma', 'dodoma'), ('mbeya', 'mbeya'), ('rukwa', 'rukwa'), ('arusha', 'arusha'), ('kilimanjaro', 'kilimanjaro'), ('dar es salaam', 'dar es saalam'), ('singida', 'singida'), ('songea', 'songea'), ('iringa', 'iringa'), ('morogoro', 'morogoro'), ('mwanza', 'mwanza'), ('kagera', 'kagera'), ('bukoba', 'bukoba'), ('songwe', 'songwe'), ('tabora', 'tabora'), ('njombe', 'njombe'), ('songwe', 'songwe'), ('kagera', 'kagera'), ('moshi', 'moshi'), ('shinyanga', 'shinyanga'), ('tanga', 'tanga'), ('musoma', 'musuma'), ('geita', 'geita')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('online_payment', 'Online Payment')], default='online_payment', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('packed', 'packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('cancel', 'cancel'), ('pending', 'pending')], default='pending', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drinks.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Drinks.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drinks.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drinks.product')),
            ],
        ),
    ]
